"""
Laboratory compliance report generation.

Produces (a) a structured dict for the UI, (b) a human-readable Markdown
report string, and (c) persisted artefacts on disk (annotated PNG + .md) so a
lab can keep an audit trail.
"""
from __future__ import annotations

import uuid
from datetime import datetime
from pathlib import Path

import cv2
import numpy as np
import pandas as pd

from . import config
from .compliance import ComplianceResult
from .detector import Detection


def build_record(
    result: ComplianceResult,
    detections: list[Detection],
    source: str,
) -> dict:
    """Assemble a JSON-serialisable report record."""
    return {
        "report_id": uuid.uuid4().hex[:8],
        "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "source": source,  # "upload" | "webcam"
        "compliance_pct": result.compliance_pct,
        "access_granted": result.access_granted,
        "detected_ppe": [i.name for i in result.checklist if i.present],
        "missing_ppe": result.missing,
        "raw_detections": [
            {"label": d.label, "confidence": round(d.confidence, 3), "box": list(d.box)}
            for d in detections
        ],
    }


def checklist_dataframe(result: ComplianceResult) -> pd.DataFrame:
    """Checklist as a DataFrame for st.dataframe / CSV export."""
    return pd.DataFrame(
        [
            {
                "PPE Item": item.name,
                "Status": "PRESENT" if item.present else "MISSING",
                "Confidence": f"{item.confidence:.0%}" if item.confidence else "-",
                "Required": "Yes" if item.required else "No",
            }
            for item in result.checklist
        ]
    )


def to_markdown(record: dict) -> str:
    """Render the record as a Markdown report."""
    decision = "🟢 ACCESS GRANTED" if record["access_granted"] else "🔴 ACCESS DENIED"
    detected = ", ".join(record["detected_ppe"]) or "None"
    missing = ", ".join(record["missing_ppe"]) or "None"

    lines = [
        "# LabPPE AI — Laboratory Compliance Report",
        "",
        f"**Report ID:** `{record['report_id']}`  ",
        f"**Timestamp:** {record['timestamp']}  ",
        f"**Source:** {record['source']}  ",
        "",
        f"## Decision: {decision}",
        "",
        f"**Compliance score:** {record['compliance_pct']:.0f}%",
        "",
        f"- **Detected PPE:** {detected}",
        f"- **Missing PPE:** {missing}",
        "",
        "## Raw detections",
        "",
        "| Class | Confidence | Box (x1, y1, x2, y2) |",
        "| --- | --- | --- |",
    ]
    for d in record["raw_detections"]:
        lines.append(f"| {d['label']} | {d['confidence']:.0%} | {tuple(d['box'])} |")
    if not record["raw_detections"]:
        lines.append("| — | — | — |")
    lines.append("")
    lines.append("_Generated by LabPPE AI._")
    return "\n".join(lines)


def save_artifacts(
    record: dict,
    annotated_rgb: np.ndarray,
    out_dir: Path | None = None,
) -> tuple[Path, Path]:
    """Persist annotated image + markdown. Returns (image_path, md_path)."""
    out_dir = out_dir or config.REPORTS_DIR
    out_dir.mkdir(parents=True, exist_ok=True)
    stem = f"report_{record['timestamp'].replace(':', '-').replace(' ', '_')}_{record['report_id']}"

    img_path = out_dir / f"{stem}.png"
    cv2.imwrite(str(img_path), cv2.cvtColor(annotated_rgb, cv2.COLOR_RGB2BGR))

    md_path = out_dir / f"{stem}.md"
    md_path.write_text(to_markdown(record), encoding="utf-8")
    return img_path, md_path
